import React from 'react';
import { UserDetails } from '../@Types/UserDetails';
import pattern from "../assets/pattern.png";

const RoastCard = React.forwardRef<HTMLDivElement, UserDetails>(
  ({ username, avatarUrl, postText, timer, new_user, error }, ref) => {
    return (
      <div
        ref={ref}
        className="position-relative bg-primary bg-gradient text-white p-4 shadow rounded-4"
        style={{
          width: '1080px',
          height: '1080px',
          overflow: 'hidden',
          backgroundImage: `url(${pattern})`,
          backgroundSize: 'cover',
          backgroundPosition: 'center',
        }}
      >
        <div className="d-flex flex-column align-items-center justify-content-center h-100 text-center position-relative" style={{ zIndex: 1 }}>
          <img 
            src={avatarUrl??""} 
            alt={username??''}
            crossOrigin="anonymous"
            className="avatar-image mb-4"
            style={{
              width: '150px',
              height: '150px',
              borderRadius: '50%',
              border: '4px solid white',
              objectFit: 'cover'
            }}
          />
          <h2 className="display-4 fw-bold mb-3">{username || 'Anonymous Coder'}</h2>
          <p className="fs-4 mb-4">Handle Rating: {error ? 'CE' : '404'}</p>

          <div className="roast-text-container bg-dark bg-opacity-75 border border-light rounded p-4 mb-4">
            <p className="roast-text fs-3 mb-0" style={{ 
              whiteSpace: 'pre-wrap',
              overflowWrap: 'break-word',
              wordWrap: 'break-word',
              maxWidth: '800px',
              margin: '0 auto',
              lineHeight: '1.4'
            }}>
              {postText || 'This roast is so weak it got TLE'}
            </p>
          </div>

          <div className="position-absolute bottom-0 w-100 text-center pb-3">
            <p className="fs-5 mb-1">
              Generated by <strong className="text-warning">RoastForce</strong>
            </p>
            <p className="text-muted small mb-0">roastforce.gg</p>
          </div>
        </div>
      </div>
    );
  }
);

export default RoastCard;
