import React from 'react';
import { UserDetails } from '../@Types/UserDetails';
import pattern from "../assets/pattern.png";
import '../styles/RoastCard.css';

const RoastCard = React.forwardRef<HTMLDivElement, UserDetails>(
  ({ username, avatarUrl, postText, timer, new_user, error }, ref) => {
    return (
      <div
        ref={ref}
        className="roast-card position-relative text-white p-4 rounded-4"
        style={{
          width: '1080px',
          height: '1080px',
        }}
      >
        {/* Background layers */}
        <div className="card-background">
          <div className="gradient-overlay"></div>
          <div className="pattern-overlay"></div>
          
          {/* Animated code elements */}
          <div className="code-elements">
            {[...Array(15)].map((_, i) => (
              <div 
                key={i} 
                className={`floating-code code-${i % 3}`}
                style={{
                  left: `${Math.random() * 100}%`,
                  top: `${Math.random() * 100}%`,
                  animationDelay: `${-Math.random() * 20}s`
                }}
              >
                {i % 3 === 0 && 'def roast(): return "🔥"'}
                {i % 3 === 1 && 'void debug() { cout << "🐛"; }'}
                {i % 3 === 2 && 'class Coffee extends ☕ { }'}
              </div>
            ))}
          </div>
        </div>

        {/* Content container with glassmorphism */}
        <div className="content-container">
          <img 
            src={avatarUrl??""} 
            alt={username??''}
            crossOrigin="anonymous"
            className="avatar-image"
          />
          <h2 className="username-text">{username || 'Anonymous Coder'}</h2>
          <p className="rating-text">Handle Rating: {error ? 'CE' : '404'}</p>

          <div className="roast-text-wrapper">
            <p className="roast-text">
              {postText || 'This roast is so weak it got TLE'}
            </p>
          </div>

          <div className="footer">
            <p className="footer-text">
              Generated by <strong className="brand-text">RoastForce</strong>
            </p>
            <p className="footer-subtext">roastforce.gg</p>
          </div>
        </div>
      </div>
    );
  }
);

export default RoastCard;
