import React from 'react';
import { UserDetails } from '../@Types/UserDetails';
import '../styles/RoastCard.css';

const RoastCard = React.forwardRef<HTMLDivElement, UserDetails>(
  ({ username, avatarUrl, postText, error }, ref) => {
    return (
      <div
        ref={ref}
        className="roast-card position-relative text-white p-4 rounded-4"
        style={{
          width: '1080px',
          height: '1080px',
        }}
      >
        {/* Background layers */}
        <div className="card-background">
          <div className="pattern-overlay"></div>
        </div>

        {/* Content container with glassmorphism */}
        <div className="content-container">
          <img 
            src={avatarUrl??""} 
            alt={username??''}
            crossOrigin="anonymous"
            className="avatar-image"
          />
          <h2 className="username-text">{username || 'Anonymous Coder'}</h2>

          <div className="roast-text-wrapper">
            <p className="roast-text">
              {postText || 'This roast is so weak it got TLE'}
            </p>
          </div>

          <div className="footer">
            <p className="footer-text text-black">
              Generated by <strong className="brand-text">roastforce.xyz</strong>
            </p>
          </div>
        </div>
      </div>
    );
  }
);

export default RoastCard;
